### ISSUE TITLE
TEMPLATE: Comic block template sends a single message with link

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#12]
Implement the comic block template so that it sends a single message with the comic.intro and adds a hyperlinked message at the bottom to follow to the comic:
Click 🔗 to read the comic

The url in the hyperlink cannot be reconstructed using the module id, Zuyi will provide all the links to be added in in a separate data list (one row per module) so the template should get the info from there

**Comment by edmoss345** [comment]
Have modified the comic template

https://docs.google.com/spreadsheets/d/1CoYl7lpd6w2xdZzE-Crt-pZT9M5dTHYFm9sWEcX5QAs/edit#gid=1693902258

HTML is to be inserted in a post translation edit

https://docs.google.com/spreadsheets/d/1UkGtEMuIQNwpquMieiOGNjMIm2O8WcZFUiM0BoHZv34/edit#gid=0

Blocked: HTML links to be provided by Zuyi

**Comment by istride** [comment]
Expecting links by Monday 11 December.

**Comment by fagiothree** [comment]
File with links: https://docs.google.com/spreadsheets/d/1n_nhPyHzc3P0mCG1cAxeSed_jogk3FEC/edit?usp=sharing&ouid=113912109700879960997&rtpof=true&sd=true

**Comment by fagiothree** [comment]
edit implemented in https://docs.google.com/spreadsheets/d/1UkGtEMuIQNwpquMieiOGNjMIm2O8WcZFUiM0BoHZv34/edit#gid=2078611847
