### ISSUE TITLE
No response from goals API

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#13]
We need to be able to use webhook calls as in https://github.com/IDEMSInternational/parenttext-goals-webhooks for defining program variables. RapidPro is hosted on a server in China so there might be problems connecting to external services that are not hosted in China.
When running a test flow in the simulator there is no response, without getting any error code
![image](https://github.com/IDEMSInternational/parenttext-china/assets/32491856/b400f675-856a-43f2-9076-c6879952be1f)

Since this feature is necessary for testing user experience, we should solve this by December 8th

**Comment by istride** [comment]
I have tried to contact the API from a server in China. Not sure what the problem is. Have asked our partner in China for suggestions.

```
curl -v 'https://X.X/get_goals_list'
*   Trying X.X.X.X:443...
* Connected to <something, something> (X.X.X.X) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, decode error (562):
* error:0A000126:SSL routines::unexpected eof while reading
* Closing connection 0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
```

**Comment by istride** [comment]
The prevailing view is that it may simply not be possible to access any Google-hosted service from within China, and we will have to consider hosting the API within China.

We can package the API as a [Docker container](https://github.com/googlecloudplatform/functions-framework-python#quickstart-build-a-deployable-container), which will allow us to deploy the API without dependence on Google services. We will need to publish the container image to a Container Registry (e.g. Docker Hub). In preparation for that, we should make sure that the container image we create is free of elements that should not or cannot be made public.
