### ISSUE TITLE
Set up system to produce completion certificates on chinese server

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#14]

**Comment by istride** [comment]
Plan is to launch at end of month.

**Comment by istride** [comment]
I have create an [issue](https://github.com/IDEMSInternational/plh-certificate-generator/issues/2) in the repo for the certificate generator that captures the more technical aspects. The China-specific issues are:

- Current font is not Unicode-compatible - no Chinese characters
- Need a new certificate template, in Chinese
- Can the certificate templates be published, or are they proprietary/secret? This will determine how and where the templates should be stored.
