### ISSUE TITLE
TEMPLATE/DATA LIST: Adjust the tips template to work with images in a separate page (budget flow)

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#15]
In addition to adding 'click the link to read the comic' to each comic.intro, we also need to include this sentence in the tips block for:
1. **budget_expenses_yc** --> tips.message.2.image, tips.message.3.image, tips.message.4.image
2. **budget_monthly_yc** --> tips.message.1.image, tips.message.4.image, tips.message.5.image

Need to rethink the block. Possible options:
* move everything to tips.intro and add a link there as for comics
* for messages containing images, instead of adding the attachment, add an html expression at the bottom: <a href="url_from_module_id">
Click to see an example
</a>

**Comment by fagiothree** [comment]
Laurie has rewritten the tip introductions and removed the tip.messages from the Google Docs. The message will include a link to a WeChat mini-article, similar to our approach with the comics.
Need to implement the edit to add the link

**Comment by fagiothree** [comment]
Edit has been implemented but chinese translation of "Click 🔗 to get started!" is missing in Crowdin

**Comment by edmoss345** [comment]
Sorry @fagiothree , when I did the initial edit I saw there was a translation for "Click the link to get started!" and used that in the sheet, but will wait until we have the finalised translation then edit as required

![image](https://github.com/IDEMSInternational/parenttext-china/assets/69303397/b2a95bad-cd70-4eaf-a46a-2cacc032f686)

**Comment by fagiothree** [comment]
Zuyi used this translation: 点击🔗链接开始学习吧！

**Comment by edmoss345** [comment]
have updated in the translation edits file, so think this can be closed
