### ISSUE TITLE
TEMPLATE: Edit video block templates so that the attachment is replaced with an html link

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#2]
The user experience will be as follows:
1. Users will receive a link prompting them to click in order to access videos
2. Clicking this link will direct them to a website where they see the videos
3. Once they've finished viewing the content, they close the link, returning to the chatbot to proceed.

Video files are sent with the text field "video.message" appearing in the data list. The block template needs to be updated to add a line of text at the bottom that reads:
⏯ Click to watch the video.

---------------------
Wenhao kindly made a video for us to show how he creates the links and how it looks like when users click them
https://photos.onedrive.com/share/F8DCE0C3A107904D!8675?cid=F8DCE0C3A107904D&resId=F8DCE0C3A107904D!8675&authkey=!AKntBRf8DbTIIeY&ithint=video&e=3E3PmX
He made three links: one connected to a WeChat Article that contains both images and pictures (and can also include gifs and videos if needed), one connected to a video, and the other one linked to an audio within WeChat filestore.

These links are just for demonstration purpose. The actual links to audios and videos will be those that Chiara showed us before, which will be connected to a structured local filestore similar to Firebase. However, to show the comics, we will need to create a series of WeChat articles.

Wenhao's demonstration scripts:
https://docs.google.com/document/d/1lA1gYcpM8xb8YqvO3TicNIaWUd0xtlb5/edit?usp=sharing&ouid=113912109700879960997&rtpof=true&sd=true

**Comment by fagiothree** [comment]
The file paths will be
Female videos:

http://file.plhparenting.cn/female/video.mp4

Male videos:

http://file.plhparenting.cn/male/video.mp4

**Comment by edmoss345** [comment]
Have localised the video within template

https://docs.google.com/spreadsheets/d/1CoYl7lpd6w2xdZzE-Crt-pZT9M5dTHYFm9sWEcX5QAs/edit#gid=1301714080

And applied a post translation edit

https://docs.google.com/spreadsheets/d/1UkGtEMuIQNwpquMieiOGNjMIm2O8WcZFUiM0BoHZv34/edit#gid=1997779499

@fagiothree could you do a bit of a sense check to see if what I've done is correct, still need to upload the globals.path variable to do some testing

**Comment by fagiothree** [comment]
Looks correct. I set up the global variable so it has the path now
