### ISSUE TITLE
Add translations in goal/module data 

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#23]
Copy translations from Crowdin files 
* https://github.com/IDEMSInternational/plh-digital-content/blob/main/translations/parent_text_v2_china/zh/zh_dictionaries%20-%20goal_names.csv
* https://github.com/IDEMSInternational/plh-digital-content/blob/main/translations/parent_text_v2_china/zh/zh_dictionaries%20-%20module_names.csv
to
https://docs.google.com/spreadsheets/d/1CoYl7lpd6w2xdZzE-Crt-pZT9M5dTHYFm9sWEcX5QAs/edit#gid=1329498385

**Comment by edmoss345** [comment]
@istride @fagiothree have copied the data across

**Comment by istride** [comment]
Update data in API for China.

**Comment by istride** [comment]
API has been updated.
