### ISSUE TITLE
Remove audio UX

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-china#24]
As a user I can choose to receive content as Text + Images or Videos + Text + Images but cannot choose to receive audio files. 

Justification: Audio is a fit-for-purpose user experience in scenarios where literacy is low and data affordability and availability is low. In China, literacy is low, but data is affordable and available. Further, with the integration of WeChat, delivery of audio messages is challenged because users cannot read alongside multimedia files appearing on WeChat microsites.

**Comment by fagiothree** [comment]
@lauriemarkle How do we edit the message:

ParentText is easiest to use when you receive content as videos, images and text. However, your data bundle and bandwidth may not support videos. To save on data, you can opt to receive the same content with a smaller audio file or as text. How would you like to receive ParentText?

**Comment by fagiothree** [comment]
edited media onboarding question and settings question to remove audio option
https://docs.google.com/spreadsheets/d/1CoYl7lpd6w2xdZzE-Crt-pZT9M5dTHYFm9sWEcX5QAs/edit#gid=821943136
https://docs.google.com/spreadsheets/d/1CoYl7lpd6w2xdZzE-Crt-pZT9M5dTHYFm9sWEcX5QAs/edit#gid=1516335137
