### ISSUE TITLE
IPV goal available to all users

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#25]
Check that changing the value in the relationship column to yes|no in the goal data sheet is all what is needed to make the IPV goal available for all users. 
Check that the template "settings_update_get_ipv" https://docs.google.com/spreadsheets/d/1lf80mIiuv_F6xAa9j5zGvXas50WxdSsLj6vrPccGNwY/edit#gid=1572639994 still makes sense

**Comment by istride** [comment]
Work done; just needs to be verified.

**Comment by fagiothree** [comment]
api calls for setting up variables are failing

**Comment by fagiothree** [comment]
problem with api solved and ipv goal working as expected

**Comment by fagiothree** [comment]
to do: test that it works as expected
