### ISSUE TITLE
Edit Consequence module

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#27]
Swap the following two sentences in the Consequence module, i.e. put the second sentence ‘Give a consequence…’ before the first sentence ‘Before giving a consequence…’, because it would work better in this way in Chinese.
![image004](https://github.com/IDEMSInternational/parenttext-china/assets/32491856/5be4547b-d76a-46f3-84f6-eb91521d539f)

edit google doc and sync with gsheet

**Comment by edmoss345** [comment]
Modified sheet and re-synced with sidekick

https://docs.google.com/document/d/1bIiU67n_4sUjm2b95Jr6p7RYu_6tTUnMKAfcskThFHo/edit
