### ISSUE TITLE
Create safeguarding json file

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#29]
From the triggers safeguarding and navigation tabs in https://docs.google.com/spreadsheets/d/1nw6IA3O2XZlN3baCCvTFMKPHnfK8-FWl/edit#gid=95643994 
create excel and json file for safeguarding, so that:
* generic and natural disaster are combined into single category (called generic)
* health and drugs combined into a single category (called health)

**Comment by edmoss345** [comment]
believe I have created the json file in #36

**Comment by fagiothree** [comment]
Update START and STOP with new translations
https://docs.google.com/spreadsheets/d/1nw6IA3O2XZlN3baCCvTFMKPHnfK8-FWl/edit#gid=1463403169
