### ISSUE TITLE
Add onboarding video 

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#37]
Need to create a local version of the "orientation" template in https://docs.google.com/spreadsheets/d/12ddvTz_ZfC-9-b0yxjVrSzczciUUE3GosLUFeOLIv9I/edit#gid=132602391
so that the attachement is replaced by the hyperlink in the text. The format of the hyperlink would be the same as for the videos in the modules (gender customised) and the name of the file is onboarding.mp4

**Comment by edmoss345** [comment]
Added a copy of the sheet in the CN localised file

https://docs.google.com/spreadsheets/d/1CoYl7lpd6w2xdZzE-Crt-pZT9M5dTHYFm9sWEcX5QAs/edit#gid=1792851506

Added the link as a post translation edits in the existing video edits sheets

https://docs.google.com/spreadsheets/d/1UkGtEMuIQNwpquMieiOGNjMIm2O8WcZFUiM0BoHZv34/edit#gid=1997779499
https://docs.google.com/spreadsheets/d/1UkGtEMuIQNwpquMieiOGNjMIm2O8WcZFUiM0BoHZv34/edit#gid=783766068

@fagiothree can you sense check if what I've done is correct

**Comment by fagiothree** [comment]
Looks good to me!
