### ISSUE TITLE
Safeguarding step in pipeline gives error

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#38]
When running the pipeline, I get the following error at the safeguarding step:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 22184: character maps to <undefined>

**Comment by fagiothree** [comment]
@edmoss345 do you get the same or does it run ok for you?

**Comment by edmoss345** [comment]
There was a problem in the pipeline reading chinese characters, think this has been resolved as part of 

https://github.com/IDEMSInternational/parenttext-pipeline/pull/73
