### ISSUE TITLE
Adjust html code to give spacing between quick replies

### ISSUE THREAD

**Issue by edmoss345** [IDEMSInternational/parenttext-china#42]
Hi Chiara and Ed, 

Many thanks for updating Crowdin. I have added the translations.
Thank you also for the quick reply options and for being so thoughtful. We would prefer the 3rd option - gap between all QR 😊

Very Best Wishes,
Zuyi

Subject: RE: Video filenames RE: path/url example - China local file store

Hi Zuyi,

Hope you’re well, Chiara and I have been doing some testing of the modules and how they appear in wechat. When we are adding the quick replies into the message text as links, there are a few options about how we space them out. The various options are shown below, what would be your preference?

![image](https://github.com/IDEMSInternational/parenttext-china/assets/69303397/f10d40e3-8604-4eb4-9c3a-56e4e8d0e753)

Thanks, Ed

**Comment by fagiothree** [comment]
Zuyi would like option 3)
