### ISSUE TITLE
LTP Activities are not showing up

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#45]
Check that the file containing LTP activities is available on the Chinese server for external API calls

**Comment by fagiothree** [comment]
this is the sheet that should be hosted: https://docs.google.com/spreadsheets/d/1tpaGJ9eljH2kD-KHKWscpR976WGNL39eUQmiFl5rgQQ/edit#gid=1136721303

**Comment by istride** [comment]
The goals API contains its own version of the models and there is an extra column in the sreadsheet ("attached_single_doc") that is causing errors in the API. I have worked around this temporarily by removing the extra column before updating the API.

**Comment by fagiothree** [comment]
The "attached_single_doc" column is created when using the sidekick, so it's okay to remove the column from the copy for the api data

**Comment by fagiothree** [comment]
tested in Wechat. Working fine now
