### ISSUE TITLE
Message is split and quick reply is not working

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#51]
Behave & safety troubleshooting : the option “I don’t want to answer” is separated into two messages. 
![image](https://github.com/IDEMSInternational/parenttext-china/assets/32491856/6366f7ab-826b-451b-b233-9b1821892d6f)
probably due to reaching the maximum amount of characters in a message.
Zuyi to Check with Wenhao the # of characters allowed within a message. Possible solutions would be to shorten the translation, or remove one option if possible.

**Comment by fagiothree** [comment]
The character limit is 1200 characters (or 600 Chinese characters). Now it seems that we have at least 42 characters more than the limit. Zuyi have tried to shorten the translations, need to test if it works. If not, Wenhao suggests that you also try to change projectid to a, because in theory, the project id can be anything.

**Comment by edmoss345** [comment]
Have completed suggested fix of changing projectid to a and updated the associated references, so this should be implemented in the China repo

**Comment by fagiothree** [comment]
Tested in wechat and working fine
