### ISSUE TITLE
TEMPLATE: Onboarding - Relationship status question

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-china#6]
Caregivers will feel uncomfortable sharing that they are widowed or divorced. They should instead be asked: 
What is your relationship status?
Press a number on your keypad:
1. Single (not in a relationship)
2. Married
3. Partnered but not married
0. Prefer not to say

**Comment by edmoss345** [comment]
Have updated the question and options to only display list as above
