### ISSUE TITLE
Urgent Parenttext China changes

### ISSUE THREAD

**Issue by edmoss345** [IDEMSInternational/parenttext-china#78]
Various changes required in China deployment, details in google doc below

https://docs.google.com/document/d/1MS5sHd5hBDhDGGXH_4GYVtQIxtzHFesBZA8UheLOmgU/edit

**Comment by edmoss345** [comment]
Have added an additional function to 'idems_translation' repo which should give desired QR functionality for China. Is not super clean as there is a lot of duplication with other functions, but given short deadlines just trying to get something that works

https://github.com/IDEMSInternational/idems_translation/pull/67

**Comment by edmoss345** [comment]
Have updated the config file in the China repo to use the updated function which should give the desired result for the China quick replies

https://github.com/IDEMSInternational/parenttext-china/pull/79

**Comment by edmoss345** [comment]
Ran the pipeline and everything seemed to work ok, just got some warnings related to some flows which were not found, @istride any idea if this is something we need to worry about?



![Image](https://github.com/IDEMSInternational/parenttext-china/assets/69303397/a1bf9fad-a2ee-4ac7-b2ed-82f1f07e521a)

**Comment by istride** [comment]
I get the same result. I think that's normal, so I would assume that it has worked.
